version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=briankibet
      - POSTGRES_PASSWORD=briankibet
      - POSTGRES_DB=fisa
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres